parameters:
- name: jdkVersion
  type: string
  default: '21'

trigger:
  branches:
    exclude:
      - renovate/*

pr:
  branches:
    include:
      - "*"

pool:
  vmImage: 'ubuntu-latest'

variables:
  GRADLE_USER_HOME: $(Pipeline.Workspace)/.gradle
  repositoryName: Account-Ledger-Cli-Kotlin-Gradle

jobs:
- job: Build
  displayName: 'Build with JDK ${{ parameters.jdkVersion }}'
  steps:
  - template: azure-pipelines-steps-template.yml
    parameters:
      jdkVersion: ${{ parameters.jdkVersion }}
