parameters:
- name: jdkVersion
  type: string
  default: '21'

jobs:
- job: Build
  displayName: 'Build with JDK ${{ parameters.jdkVersion }}'
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    GRADLE_USER_HOME: $(Pipeline.Workspace)/.gradle
    repositoryName: Account-Ledger-Cli-Kotlin-Gradle
  steps:
  - template: azure-pipelines-steps-template.yml
    parameters:
      jdkVersion: ${{ parameters.jdkVersion }}
